# https://hub.docker.com/_/python
FROM ollama/ollama:latest
LABEL maintainer="xenos <xenos.lu@gmail.com>"

# RUN ollama pull wizardlm-uncensored:13b-llama2-q4_K_S
# RUN ollama pull deepseek-coder:1.3b
# RUN ollama pull tinyllama:1.1b

